routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('root');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




// Route::get('/vente', [App\Http\Controllers\VenteController::class, 'index'])->name('vente');
// Route::get('/fetchvente', [App\Http\Controllers\VenteController::class, 'fetch'])->name('fetchvente');
// Route::get('/searchvente/{q}', [App\Http\Controllers\VenteController::class, 'search'])->name('searchvente');
// Route::get('/searchventebyid/{id}', [App\Http\Controllers\VenteController::class, 'searchventebyid'])->name('searchventebyid');
// Route::post('/postvente', [App\Http\Controllers\VenteController::class, 'store'])->name('postvente');
// Route::put('/updatevente/{id}', [App\Http\Controllers\VenteController::class, 'update'])->name('updatevente');
// Route::delete('/deletevente/{id}', [App\Http\Controllers\VenteController::class, 'destroy'])->name('deletevente');
// Route::get('/query/{date}/{circle}', [App\Http\Controllers\HomeController::class, 'query'])->name('query');

///////////////
Route::post('paycallback', [App\Http\Controllers\TransactionController::class,'paycallback'])->name('paycallback');
Route::get('forfaitwelcome', [App\Http\Controllers\TransactionController::class,'forfaitwelcome'])->name('forfaitwelcome');
Route::post('filter/ticket', [App\Http\Controllers\TicketController::class,'filter'])->name('filter.ticket');
Route::resource('cyber', App\Http\Controllers\CyberController::class);
Route::resource('package', App\Http\Controllers\PackageController::class);
Route::resource('ticket', App\Http\Controllers\TicketController::class);
Route::post('ticket/importcsv', [App\Http\Controllers\TicketController::class,'importcsv'])->name('ticket.importcsv');
Route::post('filter/cyber', [App\Http\Controllers\CyberController::class,'filter'])->name('filter.cyber');
Route::resource('vente', App\Http\Controllers\VenteController::class);

// Route::group(['as'=>'admin.','prefix'=>'admin', 'middleware'=>['admin'], 'namespace'=>'Admin'],function (){
// 	}
// );
Route::group(['as'=>'api.', 'prefix'=>'api/v1'], function (){
	Route::get('forfait', [App\Http\Controllers\TransactionController::class,'transtionbuy'])->name('transtionbuy');
	}
);

Route::resource('client', App\Http\Controllers\ClientController::class);

app/Models/Cyber.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cyber extends Model
{
    use HasFactory;

    public function ventes()
    {
        return $this->hasMany(Ventes::class);
    }
    public function packages()
    {
        return $this->hasMany(Package::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CyberController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cyber;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class CyberController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cybers = Auth::user()->cybers()->get()->all();
        // dd($cybers);
        return view('admin.cyber.index',compact(['cybers']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cyber.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $this->validate($request,[
            'cybername' => 'required',
            'ipayment' => 'required',
            'token' => 'required'
        ]);
        $user=Auth::user();
        $cyber = new Cyber();
        $cyber->name = $request->cybername;
        $cyber->gateway = $request->ipayment;
        $cyber->token = $request->token;
        $cyber->user_id = $user->id;

        $cyber->save();
        return redirect()->route('cyber.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Cyber  $cyber
     * @return \Illuminate\Http\Response
     */
    public function show(Cyber $cyber)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Cyber  $cyber
     * @return \Illuminate\Http\Response
     */
    public function edit(Cyber $cyber)
    {
        return view('admin.cyber.edit',compact(['cyber']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cyber  $cyber
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cyber $cyber)
    {
        $this->validate($request,[
            'cybername' => 'required',
            'ipayment' => 'required',
            'token' => 'required'
        ]);
        $cyber->name = $request->cybername;
        $cyber->gateway = $request->ipayment;
        $cyber->token = $request->token;
    
        $cyber->update();
        return redirect()->route('cyber.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Cyber  $cyber
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cyber $cyber)
    {
        //
    }


    public function filter(Request $request)
    {
        // dd($request->all());
        $this->validate($request,[
            'search' => 'required',
        ]);
        $cybers=Auth::user()->cybers->where('name', $request->search);
        dd($cybers);
        return redirect()->route('cyber.index');


    }
}

resources/views/admin/cyber/create.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Ajouter un cyber</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('cyber.index')}}">Cyber</a></li>
              <li class="breadcrumb-item active">Ajouter un cyber</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <!-- /.card-header -->
              <!-- form start -->
              <form method="post" action="{{ route('cyber.store') }}">
                {{csrf_field()}}
                <div class="card-body">
                  <div class="form-group">
                    <label for="cybername">Nom du cyber</label>
                    <input type="text" class="form-control" name="cybername" id="cybername" placeholder="Nom du cyber" value="{{old('name')}}">
                  </div>
                  <div class="form-group">
                    <label for="ipayment">Interface de payement</label>
                    <input type="text" class="form-control" name="ipayment" id="ipayment" placeholder="ex: Paygate global" value="{{old('ipayment')}}">
                  </div>
                  <div class="form-group">
                    <label for="token">Token</label>
                    <input type="text" class="form-control" name="token" id="token" placeholder="Token" value="{{old('token')}}">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Ajouter</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/cyber/edit.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Ajouter un cyber</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('cyber.index')}}">Cyber</a></li>
              <li class="breadcrumb-item active">Ajouter un cyber</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <!-- /.card-header -->
              <!-- form start -->
              <form method="post" action="{{ route('cyber.update', $cyber) }}">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="PUT">
                <div class="card-body">
                  <div class="form-group">
                    <label for="cybername">Nom du cyber</label>
                    <input type="text" class="form-control" name="cybername" id="cybername" placeholder="Nom du cyber" value="{{$cyber->name}}">
                  </div>
                  <div class="form-group">
                    <label for="ipayment">Interface de payement</label>
                    <input type="text" class="form-control" name="ipayment" id="ipayment" placeholder="ex: Paygate global" value="{{$cyber->gateway}}">
                  </div>
                  <div class="form-group">
                    <label for="token">Token</label>
                    <input type="text" class="form-control" name="token" id="token" placeholder="Token" value="{{$cyber->token}}">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Modifer</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/cyber/index.blade.php
@extends('layouts.admin.admin') 

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Cybers</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('cyber.index')}}">Cyber</a></li>
              <li class="breadcrumb-item active">Index</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
        <form method="post" action="{{route('filter.cyber')}}">
          {{csrf_field()}}
          <div class="row">
            <div class="col-sm-2">
              <input type="text" name="search"  placeholder="Rechercher" value="" class="form-control">
            </div>
            <div class="col-sm-2">
              <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  tabindex="-1" aria-hidden="true" name="package_id">
                {{-- @foreach($packages as $k => $v)
                  <option value="{{$v->id}}">{{$v->name}}</option>
                @endforeach --}}
                <option value="">Choisir une option</option>
                <option value="">Option  1</option>
                <option value="">Option  2</option>
              </select>
            </div>
            <div class="col-sm-2">
              <button type="submit" class="btn btn-success btn-md mb-2">Valider</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <a type="button" class="btn btn-primary btn-lg float-sm-right mb-2" href="{{route('cyber.create')}}">Ajouter un cyber</a>
          </div>

          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listes de vos cybers</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">Id</th>
                      <th>Nom</th>
                      <th>Interface</th>
                      <th>Token</th>
                      <th style="width: 40px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($cybers as $k => $v)
                    <tr>
                      <td>{{$k+1}}</td>
                      <td>{{$v->name}}</td>
                      <td>{{$v->gateway}}</td>
                      <td>{{$v->token}}</td>
                      <td>
                        <a class="btn btn-primary" href="{{route('cyber.edit',$v)}}">edit</a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="#">«</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection