routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('root');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




// Route::get('/vente', [App\Http\Controllers\VenteController::class, 'index'])->name('vente');
// Route::get('/fetchvente', [App\Http\Controllers\VenteController::class, 'fetch'])->name('fetchvente');
// Route::get('/searchvente/{q}', [App\Http\Controllers\VenteController::class, 'search'])->name('searchvente');
// Route::get('/searchventebyid/{id}', [App\Http\Controllers\VenteController::class, 'searchventebyid'])->name('searchventebyid');
// Route::post('/postvente', [App\Http\Controllers\VenteController::class, 'store'])->name('postvente');
// Route::put('/updatevente/{id}', [App\Http\Controllers\VenteController::class, 'update'])->name('updatevente');
// Route::delete('/deletevente/{id}', [App\Http\Controllers\VenteController::class, 'destroy'])->name('deletevente');
// Route::get('/query/{date}/{circle}', [App\Http\Controllers\HomeController::class, 'query'])->name('query');

///////////////
Route::post('paycallback', [App\Http\Controllers\TransactionController::class,'paycallback'])->name('paycallback');
Route::get('forfaitwelcome', [App\Http\Controllers\TransactionController::class,'forfaitwelcome'])->name('forfaitwelcome');
Route::post('filter/ticket', [App\Http\Controllers\TicketController::class,'filter'])->name('filter.ticket');
Route::resource('cyber', App\Http\Controllers\CyberController::class);
Route::resource('package', App\Http\Controllers\PackageController::class);
Route::resource('ticket', App\Http\Controllers\TicketController::class);
Route::post('ticket/importcsv', [App\Http\Controllers\TicketController::class,'importcsv'])->name('ticket.importcsv');
Route::post('filter/cyber', [App\Http\Controllers\CyberController::class,'filter'])->name('filter.cyber');
Route::resource('vente', App\Http\Controllers\VenteController::class);

// Route::group(['as'=>'admin.','prefix'=>'admin', 'middleware'=>['admin'], 'namespace'=>'Admin'],function (){
// 	}
// );
Route::group(['as'=>'api.', 'prefix'=>'api/v1'], function (){
	Route::get('forfait', [App\Http\Controllers\TransactionController::class,'transtionbuy'])->name('transtionbuy');
	}
);

Route::resource('client', App\Http\Controllers\ClientController::class);

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function package()
    {
        return $this->belongsTo(Package::class);
    }
    public function ventes()
    {
        return $this->hasMany(Vente::class);
    }
    
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ticket;
use App\Models\Package;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class TicketController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // faire un orderBy
        $packages = Auth::user()->packages()->get()->all();
        $tickets = Auth::user()->tickets()->paginate(10);
        return view('admin.ticket.index',compact(['packages', 'tickets']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.ticket.create');
    }

    public function importcsv(Request $request)
    {
        $this->validate($request,[
        'package_id'=> 'required',
        // 'csvFile'=>'mimes',
        ]);

        $file = $request->file('csvFile');
        $content = fopen($file,'r');

        $idIndex = $request->id;
        $paswordIndex = $request->password;
        $user=Auth::user();
        $ticketPice = Package::find($request->package_id)->price;

        while(($line = fgetcsv($content)) !== false){
        $ticketName = $line[$idIndex-1];
        $ticketPass = $line[$paswordIndex-1];
            if ($ticketName !== null && $ticketName !== '') {
                $ticket = new Ticket();
                $ticket->user_id = $user->id;
                $ticket->package_id = $request->package_id;
                $ticket->name = $ticketName;
                $ticket->price = $ticketPice;
                // $ticket->password = $ticketPass;
                $ticket->save();
            }
        }
        fclose($content);
        
        return redirect()->route('ticket.index');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ticket $ticket)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        //
    }

    public function filter(Request $request)
    {
        // dd($request->all());
        $tickets=Auth::user()->tickets();
        if (!is_null($request->status)) {
            $tickets= $tickets->where('status', $request->status);
        }
        if (!is_null($request->search)) {
            
        }
        $tickets= $tickets->paginate(10);
        $packages = Auth::user()->packages()->get()->all();
        return view('admin.ticket.index',compact(['packages', 'tickets']));

    }
}

resources/views/admin/ticket/create.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Cybers</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('cyber.index')}}">Cyber</a></li>
              <li class="breadcrumb-item active">Ajouter un cyber</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Quick Example</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form>
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="exampleInputFile">
                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text">Upload</span>
                      </div>
                    </div>
                  </div>
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Ajouter</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/ticket/index.blade.php
@extends('layouts.admin.admin')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Tickets</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('ticket.index')}}">Ticket</a></li>
              <li class="breadcrumb-item active">Listes</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
        <form method="post" action="{{route('filter.ticket')}}">
          {{csrf_field()}}
          <div class="row">
            <div class="col-sm-2">
              <input type="text" name="search"  placeholder="Rechercher" value="" class="form-control">
            </div>
            <div class="col-sm-2">
              <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  tabindex="-1" aria-hidden="true" name="status">
                {{-- @foreach($packages as $k => $v)
                  <option value="{{$v->id}}">{{$v->name}}</option>
                @endforeach --}}
                <option value="">Choisir un status</option>
                <option value="2">En entente</option>
                <option value="0">Non vendu</option>
                <option value="1">Vendu</option>
              </select>
            </div>
            <div class="col-sm-2">
              <button type="submit" class="btn btn-success btn-md mb-2">Valider</button>
            </div>
          </div>
        </form>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <button type="button" class="btn btn-primary btn-lg float-sm-right mb-2" href="{{route('ticket.create')}}" data-toggle="modal" data-target="#modal-sm" >Ajouter des tickets</a>
          </div>

          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listes de vos tickets</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">Id</th>
                      <th>Nom d'utilisateur</th>
                      <th>Mot de passe</th>
                      <th>Prix</th>
                      <th>Etat</th>
                      <th style="width: 40px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($tickets as $k => $v)
                    <tr>
                      <td>{{$k+1}}</td>
                      <td>{{$v->name}}</td>
                      <td>{{$v->password}}</td>
                      <td>{{$v->price}}</td>
                      <td>
                        @if ($v->status == 0) 
                        <span class="right badge badge-success">Valide</span> 
                        @elseif ($v->status == 1)
                        <span class="right badge badge-danger">Vendu</span> 
                        @elseif ($v->status == 2)
                        <span class="right badge badge-warning">Entente</span>
                        @endif
                      </td>
                      <td>
                        <a class="btn btn-primary" href="{{route('ticket.edit',$v)}}">Invalider</a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="d-flex justify-content-center">
                {!! $tickets->links() !!}
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->

    <div class="modal fade" id="modal-sm" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Choisir votre fichier</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <form method="post" action="{{ route('ticket.importcsv') }}" enctype="multipart/form-data">
              {{csrf_field()}}
              <div class="modal-body">
                <div class="form-group">
                  <label for="csvFile">Fichier CSV</label>
                  <div class="input-group">
                    <div class="custom-file">
                      <input type="file" name="csvFile" class="custom-file-input" id="csvFile" accept=".csv">
                      <label class="custom-file-label" for="csvFile">Choisir csv</label>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                    <label>Forfait</label>
                    <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  tabindex="-1" aria-hidden="true" name="package_id">
                      @foreach($packages as $k => $v)
                        <option value="{{$v->id}}">{{$v->name}}</option>
                      @endforeach
                    </select>
                  </div>
              </div>
              <div class="form-group">
                    <label>Colonne d'identifiant</label>
                    <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  tabindex="-1" aria-hidden="true" name="id">
                      <option value="1" selected>1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                      <option value="5">5</option>
                      <option value="6">6</option>
                      <option value="7">7</option>
                      <option value="8">8</option>
                      <option value="9">9</option>
                      <option value="10">10</option>
                    </select>
                  </div>
              </div>
              <div class="form-group">
                    <label>Colonne de mot de passe</label>
                    <select class="form-control select2 select2-hidden-accessible" style="width: 100%;"  tabindex="-1" aria-hidden="true" name="password">
                      <option value="1">1</option>
                      <option value="2" selected>2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                      <option value="5">5</option>
                      <option value="6">6</option>
                      <option value="7">7</option>
                      <option value="8">8</option>
                      <option value="9">9</option>
                      <option value="10">10</option>
                    </select>
                  </div>
              </div>
              <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                <button type="submit" class="btn btn-primary">Envoyer</button>
              </div>
            </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
  </div>
@endsection